// Exercise the settings listener against an in-process Wayland server. The
// socket pair avoids a compositor, window, and changes to desktop settings.
#define _POSIX_C_SOURCE 200809L
#include <GLFW/glfw3.h>
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <system/input_repeat.h>
#include <unistd.h>
#include <wayland-server-protocol.h>
#include <wayland-server.h>

static struct wl_resource *seat;
static struct wl_resource *keyboard;
static struct wl_display *server;

int glfwGetPlatform(void) { return GLFW_PLATFORM_WAYLAND; }

static void keyboard_destroyed(struct wl_resource *resource) {
  (void)resource;
  keyboard = NULL;
}

static void release_keyboard(struct wl_client *client, struct wl_resource *resource) {
  (void)client;
  wl_resource_destroy(resource);
}

static const struct wl_keyboard_interface keyboard_impl = {.release = release_keyboard};

static void get_keyboard(struct wl_client *client, struct wl_resource *resource, uint32_t id) {
  keyboard = wl_resource_create(client, &wl_keyboard_interface, wl_resource_get_version(resource), id);
  assert(keyboard);
  wl_resource_set_implementation(keyboard, &keyboard_impl, NULL, keyboard_destroyed);
  wl_keyboard_send_repeat_info(keyboard, 25, 650);
}

static const struct wl_seat_interface seat_impl = {.get_keyboard = get_keyboard};

static void bind_seat(struct wl_client *client, void *data, uint32_t version, uint32_t id) {
  (void)data;
  seat = wl_resource_create(client, &wl_seat_interface, version, id);
  assert(seat);
  wl_resource_set_implementation(seat, &seat_impl, NULL, NULL);
  wl_seat_send_capabilities(seat, WL_SEAT_CAPABILITY_KEYBOARD);
}

static input_repeat_settings_t pump(void) {
  assert(wl_event_loop_dispatch(wl_display_get_event_loop(server), 0) >= 0);
  wl_display_flush_clients(server);
  return input_repeat_settings();
}

static void expect_settings(bool enabled, double delay, double interval) {
  input_repeat_settings_t settings = {0};
  // Each pump handles a nonblocking frame, including requests generated by
  // the preceding registry and seat events. No roundtrip blocks the editor.
  for (int i = 0; i < 20; ++i)
    settings = pump();
  assert(settings.enabled == enabled);
  assert(fabs(settings.delay - delay) < 1e-9);
  assert(fabs(settings.interval - interval) < 1e-9);
}

int main(void) {
  int sockets[2];
  assert(socketpair(AF_UNIX, SOCK_STREAM, 0, sockets) == 0);
  server = wl_display_create();
  assert(server);
  struct wl_client *client = wl_client_create(server, sockets[0]);
  assert(client);
  struct wl_global *global = wl_global_create(server, &wl_seat_interface, 4, NULL, bind_seat);
  assert(global);
  char socket_env[32];
  snprintf(socket_env, sizeof(socket_env), "%d", sockets[1]);
  assert(setenv("WAYLAND_SOCKET", socket_env, 1) == 0);
  input_repeat_init();
  input_repeat_settings_t settings = input_repeat_settings();
  assert(!settings.enabled); // Not yet received from the compositor.
  expect_settings(true, 0.65, 0.04);
  assert(keyboard);

  wl_keyboard_send_repeat_info(keyboard, 40, 300);
  expect_settings(true, 0.3, 0.025);
  wl_keyboard_send_repeat_info(keyboard, 0, 300);
  expect_settings(false, 0.3, 0.0);
  wl_keyboard_send_repeat_info(keyboard, 20, 500);
  expect_settings(true, 0.5, 0.05);

  wl_seat_send_capabilities(seat, 0);
  expect_settings(false, 0.0, 0.0);
  assert(!keyboard);
  wl_seat_send_capabilities(seat, WL_SEAT_CAPABILITY_KEYBOARD);
  expect_settings(true, 0.65, 0.04);
  wl_global_remove(global);
  expect_settings(false, 0.0, 0.0);
  wl_client_destroy(client);
  assert(!input_repeat_settings().enabled);
  input_repeat_shutdown();
  wl_global_destroy(global);
  wl_display_destroy(server);
  puts("Wayland system repeat settings tests passed");
  return 0;
}
